// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only needed to *generate* a migration — `prisma migrate diff` against the
    // migrations directory replays them into a throwaway database to work out
    // the delta. Never used by the running app, and unset in production.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
